name: Build PokePlayer Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Temurin (OpenJDK)
          java-version: '17'     # Use Java 17 (required for Minecraft 1.18.2)

      # Step 3: Cache Gradle Dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-artifacts
          path: build/libs/*.jar
