0name: Build PokePlayer Mod

on:
  push:
    branches:
      - codespace-super-couscous-764wj5rwj6crxrr
  pull_request:
    branches:
      - codespace-super-couscous-764wj5rwj6crxrr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Checkout the other repository (Pokecube-Issues-and-Wiki)
    - name: Checkout Pokecube-Issues-and-Wiki
      run: |
        git clone --branch 1.18.2 https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki.git
        cp -r Pokecube-Issues-and-Wiki/src/* ./src/

    # Step 3: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 4: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 5: Build the mod
    - name: Build the mod
      run: ./gradlew build

    # Step 6: Upload the built JAR artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pokeplayer-mod
        path: build/libs/*.jar

				# Debug check
				name: Debug build directory
       run: ls -R build