name: Build Pokecube Pokeplayer Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK 17 (required for Minecraft 1.18.2)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies to speed up builds, but allow refresh
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      # Make gradlew executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Test Maven repository connectivity
      - name: Test Maven Repositories
        run: |
          echo "Testing Forge Maven..."
          curl -I https://files.minecraftforge.net/maven
          echo "Testing CurseMaven..."
          curl -I https://cursemaven.com
          echo "Testing Maven Central..."
          curl -I https://repo1.maven.org/maven2

      # Clean and build with Gradle, forcing dependency refresh
      - name: Build with Gradle
        run: ./gradlew clean build --refresh-dependencies --stacktrace --info

      # Upload the built JAR as an artifact (even if build fails)
      - name: Upload Mod JAR
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mod-jar
          path: build/libs/*.jar
          if-no-files-found: ignore

      # Upload Gradle logs for debugging
      - name: Upload Gradle Logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: gradle-logs
          path: |
            build/reports/
            ~/.gradle/
          if-no-files-found: warn