name: Build PokePlayer Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the main repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Sparse checkout of specific folders from Pokecube-Issues-and-Wiki repository
    - name: Sparse checkout Pokecube-Issues-and-Wiki repository
      run: |
        git init Pokecube-Issues-and-Wiki
        cd Pokecube-Issues-and-Wiki
        git remote add origin https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki.git
        git config core.sparseCheckout true
        echo "src/" >> .git/info/sparse-checkout
        echo "ThutCore/" >> .git/info/sparse-checkout
        git fetch --depth 1 origin 1.18.2
        git checkout 1.18.2

    # Step 3: Set up Java Development Kit (JDK 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 4: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 5: Run the Gradle build
    - name: Build the mod
      run: ./gradlew build